name: Update Trading Journal

on:
  schedule:
    - cron: '*/30 * * * *' # каждые 30 минут
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests notion-client
      - name: Run trading journal update
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: python trading_journal.py
